seed: 42
data:
  images_dir: data/synth/images
  ann_file: data/synth/annotations.json
  img_size: [512, 512]
  heatmap_sigma: 3.0
  train_val_split: 0.9
train:
  epochs: 5
  batch_size: 1
  lr: 3e-4
  weight_decay: 1e-4
  workers: 4
  adv:
    use_fgsm: true
    epsilon: 0.015
model:
  in_channels: 3
  num_keypoints: 4
  base_channels: 32
loss:
  w_visibility: 0.2
  w_homography: 0.1
out_dir: runs
